spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=GMT%2B8
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: warn
    com.qiufeng: info
  file: log/blog-pro.log

